#:schema node_modules/wrangler/config-schema.json
name = "taquin"
compatibility_date = "2024-07-18"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_flags = [ "nodejs_compat" ]
[vars]
API_VERSION="4.79.0"
USER_AGENT="Mozilla/5.0 (X11; Linux x86_64; rv:137.0) Gecko/20100101 Firefox/137.0"
PUBLIC_BANNER = false
PUBLIC_BANNER_TEXT = "Rien d'inquiétant..."
